### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by sokra** [webpack/analyse-tool#3]
- [x] Find a team (until 18.11.)
- [x] Select team leaders (until 22.11.)
- [x] Gather a list of features we want to implement (ordered by importance) (until 25.11.)
- [x] Plan the UI (multiple pages?)
- [x] Bootstrap the basic infrastructure
  - [x] router
  - [x] store
  - [x] pages
  - [x] folders (pages?, components?)
- [ ] Implement basic loading of webpack stats
- [ ] Split the work into multiple features (on which can be worked async)
  - [ ] user friendly loading of webpack stats
- [ ] Setup infrastructure for publishing as web app (codeship?, gh-pages?)
- [x] Infrastructure optimization (Code Splitting)
- [ ] Setup infrastructure for building as electron app

**Comment by bartekus** [comment]
As of right now, a lot of basic have been established as I've transferred a lot of functionality from other projects that I've been working on. I'll try to keep the momentum going and hopefully we'll get this out the door before new year!
